server:
  port: ${PORT:9091}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/${DB:erlangshen}?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: ${DB_USER:root}
    password: ${DB_PWD:123456}
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: ${DRUID_PWD:123456}
      filter:
        slf4j:
          enabled: true
          statement-log-enabled: false
          connection-log-enabled: false
          result-set-log-enabled: true
          statement-executable-sql-log-enable: true

logging:
  config: classpath:config/log4j2.xml

mybatis:
  config-location: classpath:config/mybatis.xml
  mapper-locations: classpath:sqlMapper/*.xml

fastjava:
  options-auhority: true
  exception:
    response-ok: true


aes:
  secret: ${SECRET:123QWE}  #数据加密秘钥

token:
  active:
    time: 35 #token有效时间 30分钟
    new: 5   #token有效期剩余多少分钟后，生成新token

validate:
  code:
    active: 600 #验证code有效时间
    reSend: 60  #验证码获取间隔

# check mail url
check:
  mail: http://erlangshen.pighand.com/user/checkMail
default:
  redirect: http://erlangshen.pighand.com

path:
  idcard: static\\images\\idcard\\  #身份证图片存放地址

#百度地图（根据ip查询城市）
bdmap:
  api:
    ip: http://api.map.baidu.com/location/ip?ip=%s&ak=%s&coor=bd09ll #查询ip地址接口
  ak: ${BDMAP_AK:xxx}
  qps:
    value: 100  #qps
    max: 100000 #最大访问量

# 百度云（身份证识别）
bdyun:
  appid: ${BDYUN_ID:xxx}
  ak: ${BDYUN_AK:xxx}
  sk: ${BDYUN_SK:xxx}
  idcard:
    qps:
      value: 10
      max: 500